/**
 * WHP Standing: Proof-of-Standing Escrow Condition
 * Wheeler Hubbell Publishing — Standing Mark Protocol
 * 
 * Enables autonomous agents, swarms, and smart contracts to require a valid,
 * signed WHP Standing Mark or verification check as an algorithmic release condition.
 */

import { evaluateStanding } from './index.mjs';

/**
 * Validates that an agent deliverable or task output meets epistemic standing
 * requirements before releasing escrowed funds or authorizing settlement.
 * 
 * @param {Object} output - The output or task deliverable generated by an agent.
 * @param {Object} standingRecord - The WHP Standing Record or Evaluation.
 * @param {Object} options - Validation constraints (minIssuedAt, maxAgeSeconds, expectedStatus).
 * @returns {Object} Escrow condition verification result.
 */
export function verifyStandingReleaseCondition(output, standingRecord, options = {}) {
  const checks = [];
  const add = (id, pass, note) => checks.push({ id, pass, ...(note ? { note } : {}) });

  // 1. Structure check
  add('record_present', !!standingRecord && typeof standingRecord === 'object', 'Standing record must be present');
  
  if (!standingRecord) {
    return {
      satisfied: false,
      code: 'MISSING_STANDING_RECORD',
      checks,
      message: 'Escrow condition failed: no standing record provided.'
    };
  }

  const record = standingRecord.record || standingRecord;
  const sig = standingRecord.signature;

  // 2. Issuer verification
  add('valid_issuer', !!record.issuer, 'Issuer must be identified');

  // 3. Subject and Claim alignment
  const subjectMatches = !options.expectedSubject || record.input?.subject === options.expectedSubject;
  add('subject_aligned', subjectMatches, options.expectedSubject ? `Matches expected subject: ${options.expectedSubject}` : 'Subject present');

  // 4. Temporal validity window
  const now = Math.floor(Date.now() / 1000);
  if (record.valid_until) {
    add('not_expired', now <= record.valid_until, `Valid until ${record.valid_until}, current time ${now}`);
  }
  if (options.maxAgeSeconds && record.issued_at) {
    add('max_age', now - record.issued_at <= options.maxAgeSeconds, `Issued within ${options.maxAgeSeconds}s`);
  }

  // 5. Epistemic status threshold (e.g. require 'observation', 'report', or 'finding')
  if (options.allowedStatuses && record.determination) {
    const status = record.determination.epistemic_status;
    const okStatus = options.allowedStatuses.includes(status);
    add('epistemic_status_threshold', okStatus, `Allowed statuses: ${options.allowedStatuses.join(', ')}`);
  }

  // 6. Structural completeness check
  if (record.determination?.checks) {
    const passedAllChecks = record.determination.checks.every(c => c.pass === true);
    add('structural_checks_passed', passedAllChecks, 'All internal structural assertions passed');
  }

  const failed = checks.filter(c => !c.pass);
  const satisfied = failed.length === 0;

  return {
    satisfied,
    code: satisfied ? 'ESCROW_RELEASE_WARRANTED' : 'ESCROW_CONDITIONS_UNMET',
    checks,
    failed: failed.map(c => c.id),
    record_hash: standingRecord.record_hash,
    signature_present: !!sig,
    message: satisfied
      ? 'Standing release condition met. Escrow may disburse to agent.'
      : `Escrow release denied: failed checks [${failed.map(c => c.id).join(', ')}].`
  };
}

/**
 * Creates an escrow condition definition compatible with agent payment protocols.
 */
export function createStandingEscrowContract(params) {
  return {
    protocol: 'whp-standing-escrow-v1',
    agent_recipient: params.recipient,
    amount: params.amount,
    currency: params.currency || 'USDC',
    network: params.network || 'eip155:8453',
    release_condition: {
      type: 'PROOF_OF_STANDING',
      verifier_door: params.verifierDoor || '/v1/audit',
      required_elements: [
        'provenance.source',
        'provenance.authority',
        'provenance.evidence',
        'epistemic_status'
      ],
      allowed_statuses: params.allowedStatuses || ['observation', 'report', 'finding'],
      require_signed_record: params.requireSigned !== false
    }
  };
}
